
# General Config
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
    jpa:
      hibernate:
        ddl-auto: none
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          globally_quoted_identifiers: true
          default_schema: ${SPRING_DATABASE_SCHEMA}
          dialect: org.hibernate.dialect.PostgreSQLDialect
    cache:
      type: redis
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      jedis:
        pool:
          max-total: 16
          max-idle: 8
          min-idle: 4
    kafka:
      consumer:
        bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
        group-id: ${KAFKA_GROUP_ID}
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

          
logging:
  level:
    com: 
      lsoftware:
        voting: info   